# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/1.5.0/tools/projmgr/schemas/cdefault.schema.json

default:
  compiler: AC6

  misc:
    - for-compiler: AC6
      ASM:
        - -masm=auto
      C-CPP:
        - -fno-rtti
        - -funsigned-char
        - -fshort-enums
        - -fshort-wchar
        - -ffunction-sections
        - -Wno-packed
        - -Wno-missing-variable-declarations
        - -Wno-missing-prototypes
        - -Wno-missing-noreturn
        - -Wno-sign-conversion
        - -Wno-nonportable-include-path
        - -Wno-reserved-id-macro
        - -Wno-reserved-identifier
        - -Wno-unused-macros
        - -Wno-documentation-unknown-command
        - -Wno-documentation
        - -Wno-license-management
        - -Wno-parentheses-equality
      Link:
        - --diag_suppress 6439,6314
        - --strict
        - --entry=Reset_Handler
      C:
        - -std=c99
      CPP:
        - -std=c++14
        - -fno-exceptions
