/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0-dev3
 *
 * Project: 'microspeech.Release+B-U585I-IOT02A' 
 * Target:  'Release+B-U585I-IOT02A' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common:1.2.0 */
#define USE_HAL_DRIVER
/* Keil::Device:STM32Cube LL:Common:1.2.0 */
#define USE_FULL_LL_DRIVER
/* tensorflow::Machine Learning:TensorFlow:Kernel:CMSIS-NN:1.22.5-rc4 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
