/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0-dev3
 *
 * Project: 'microspeech.Release+B-U585I-IOT02A' 
 * Target:  'Release+B-U585I-IOT02A' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32u5xx.h"

/* ARM::CMSIS-Compiler:I/O:STDERR:User:1.0.0 */
#define RTE_Compiler_IO_STDERR          /* Compiler I/O: STDERR */
        #define RTE_Compiler_IO_STDERR_User     /* Compiler I/O: STDERR User */
/* ARM::CMSIS-Compiler:I/O:STDIN:User:1.0.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
        #define RTE_Compiler_IO_STDIN_User      /* Compiler I/O: STDIN User */
/* ARM::CMSIS-Compiler:I/O:STDOUT:User:1.0.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
        #define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* ARM::CMSIS-View:Event Recorder:DAP:1.5.2 */
#define RTE_CMSIS_View_EventRecorder
        #define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS:RTOS2:Keil RTX5:Source:5.5.4 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:SPI:1.1.0 */
#define RTE_Drivers_SPI1                /* Driver SPI1 */
        #define RTE_Drivers_SPI2                /* Driver SPI2 */
        #define RTE_Drivers_SPI3                /* Driver SPI3 */
/* Keil::CMSIS Driver:USART:1.2.0 */
#define RTE_Drivers_USART1              /* Driver USART1 */
        #define RTE_Drivers_USART2              /* Driver USART2 */
        #define RTE_Drivers_USART3              /* Driver USART3 */
        #define RTE_Drivers_USART4              /* Driver USART4 */
        #define RTE_Drivers_USART5              /* Driver USART5 */
        #define RTE_Drivers_USART6              /* Driver USART6 */
/* Keil::CMSIS Driver:USB Device:Full-speed:1.0.0 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
/* Keil::CMSIS Driver:VIO:Board:B-U585I-IOT02A:1.2.0 */
#define RTE_VIO_BOARD
        #define RTE_VIO_B_U585I_IOT02A
/* Keil::CMSIS Driver:WiFi:EMW3080:SPI:1.0.0 */
#define RTE_Drivers_WiFi_EMW3080_SPI_B_U585I_IOT02A
/* Keil::Device:STM32Cube Framework:STM32CubeMX:2.0.0 */
#define RTE_DEVICE_FRAMEWORK_CUBE_MX
/* Keil::Device:STM32Cube HAL:ADC:1.2.0 */
#define RTE_DEVICE_HAL_ADC
/* Keil::Device:STM32Cube HAL:Common:1.2.0 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device:STM32Cube HAL:Cortex:1.2.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device:STM32Cube HAL:DMA:1.2.0 */
#define RTE_DEVICE_HAL_DMA
/* Keil::Device:STM32Cube HAL:EXTI:1.2.0 */
#define RTE_DEVICE_HAL_EXTI
/* Keil::Device:STM32Cube HAL:Flash:1.2.0 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device:STM32Cube HAL:GPIO:1.2.0 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device:STM32Cube HAL:HCD:1.2.0 */
#define RTE_DEVICE_HAL_HCD
/* Keil::Device:STM32Cube HAL:I2C:1.2.0 */
#define RTE_DEVICE_HAL_I2C
/* Keil::Device:STM32Cube HAL:ICACHE:1.2.0 */
#define RTE_DEVICE_HAL_ICACHE
/* Keil::Device:STM32Cube HAL:IRDA:1.2.0 */
#define RTE_DEVICE_HAL_IRDA
/* Keil::Device:STM32Cube HAL:MDF:1.2.0 */
#define RTE_DEVICE_HAL_MDF
/* Keil::Device:STM32Cube HAL:OSPI:1.2.0 */
#define RTE_DEVICE_HAL_OSPI
/* Keil::Device:STM32Cube HAL:PCD:1.2.0 */
#define RTE_DEVICE_HAL_PCD
/* Keil::Device:STM32Cube HAL:PWR:1.2.0 */
#define RTE_DEVICE_HAL_PWR
/* Keil::Device:STM32Cube HAL:RCC:1.2.0 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device:STM32Cube HAL:RNG:1.2.0 */
#define RTE_DEVICE_HAL_RNG
/* Keil::Device:STM32Cube HAL:RTC:1.2.0 */
#define RTE_DEVICE_HAL_RTC
/* Keil::Device:STM32Cube HAL:SAI:1.2.0 */
#define RTE_DEVICE_HAL_SAI
/* Keil::Device:STM32Cube HAL:SPI:1.2.0 */
#define RTE_DEVICE_HAL_SPI
/* Keil::Device:STM32Cube HAL:Smartcard:1.2.0 */
#define RTE_DEVICE_HAL_SMARTCARD
/* Keil::Device:STM32Cube HAL:UART:1.2.0 */
#define RTE_DEVICE_HAL_UART
/* Keil::Device:STM32Cube HAL:USART:1.2.0 */
#define RTE_DEVICE_HAL_USART
/* Keil::Device:STM32Cube LL:Common:1.2.0 */
#define RTE_DEVICE_LL_COMMON
/* Keil::Device:STM32Cube LL:DLYB:1.2.0 */
#define RTE_DEVICE_LL_DLYB
/* Keil::Device:STM32Cube LL:GPIO:1.2.0 */
#define RTE_DEVICE_LL_GPIO
/* Keil::Device:STM32Cube LL:PWR:1.2.0 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device:STM32Cube LL:RCC:1.2.0 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device:STM32Cube LL:UCPD:1.2.0 */
#define RTE_DEVICE_LL_UCPD
/* Keil::Device:STM32Cube LL:UTILS:1.2.0 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device:Startup:Source C:1.0.0 */
#define RTE_DEVICE_STARTUP_STM32U5XX    /* Device Startup for STM32U5 */
/* tensorflow::Data Exchange:Serialization:flatbuffers:tensorflow:1.22.5-rc4 */
#define RTE_DataExchange_Serialization_flatbuffers     /* flatbuffers */
/* tensorflow::Data Processing:Math:gemmlowp fixed-point:tensorflow:1.22.5-rc4 */
#define RTE_DataExchange_Math_gemmlowp     /* gemmlowp */
/* tensorflow::Data Processing:Math:kissfft:tensorflow:1.22.5-rc4 */
#define RTE_DataExchange_Math_kissfft     /* kissfft */
/* tensorflow::Data Processing:Math:ruy:tensorflow:1.22.5-rc4 */
#define RTE_DataProcessing_Math_ruy     /* ruy */
/* tensorflow::Machine Learning:TensorFlow:Kernel:CMSIS-NN:1.22.5-rc4 */
#define RTE_ML_TF_LITE     /* TF */


#endif /* RTE_COMPONENTS_H */
